-- ===================================
-- EXPLORATORY DATA ANALYSIS
-- ====================================

-- Explore tables in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore columns of gold layer tables or Views
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'gold_%';

-- Explore all objects in the Databases
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all columns in the Databases
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold_fact_sales';

-- Explore all countries our customers come from
SELECT DISTINCT country FROM gold_dim_customers;

-- Explore all categories 'The Major Divisions'
SELECT DISTINCT category, subcategory, product_name FROM gold_dim_products
ORDER BY 1,2,3;

-- Find date of first and last order
SELECT
MIN(order_date) AS first_order_date,
Max(order_date) AS last_order_date,
TIMESTAMPDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold_fact_sales;

-- Find youngest and oldest customers
SELECT
MIN(birthdate) AS oldest_customer_birthdate,
TIMESTAMPDIFF(year, MIN(birthdate), NOW()) AS oldest_customer_age,
MAX(birthdate) AS youngest_customer_birthdate,
TIMESTAMPDIFF(year, MAX(birthdate), NOW()) AS youngest_customer_age,
TIMESTAMPDIFF(year, MIN(birthdate), MAX(birthdate)) AS birtdate_range
FROM gold_dim_customers;

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold_fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold_fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_selling_price FROM gold_fact_sales;

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold_fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold_fact_sales;

-- Find the Total number of Products
SELECT COUNT(product_key) AS total_products FROM gold_dim_products;
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold_dim_products;

-- Find the Total number of Customers
SELECT COUNT(customer_key) total_customers FROM gold_dim_customers;
SELECT COUNT(DISTINCT customer_key) total_customers FROM gold_dim_customers;

-- Find the Total number of Customers that have placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers_with_an_order FROM gold_fact_sales;

-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold_fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold_fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold_fact_sales
UNION ALL
SELECT 'Total Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold_fact_sales
UNION ALL
SELECT 'Total Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM gold_dim_products
UNION ALL
SELECT 'Total Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold_dim_customers;

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY country;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) total_customers
FROM gold_dim_customers
GROUP BY gender;

-- Find total products by category
SELECT
category,
COUNT(product_name) AS total_products
FROM gold_dim_products
GROUP BY category;

-- What is the average cost in each category?
SELECT
category,
AVG(COALESCE(product_cost, 0)) AS avg_cost
FROM gold_dim_products
GROUP BY category;

-- What is the total revenue generated for each category?
SELECT 
p.category, 
SUM(s.sales_amount) AS sales
FROM gold_fact_sales s
LEFT JOIN gold_dim_products p
ON p.product_key = s.product_key
GROUP BY category;

-- Find total revenue generated by each customer
SELECT
	c.first_name,
	c.last_name,
	f.customer_key,
	SUM(sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
ON f.customer_key = c.customer_key
GROUP BY first_name, last_name, customer_key
ORDER BY total_revenue DESC;

-- What is the distribution of items sold across countries?
SELECT 
	c.country, 
	COUNT(s.quantity) AS items_sold 
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON c.customer_key = s.customer_key
GROUP BY country
ORDER BY items_sold DESC;

-- Which 5 products generate the highest revenue?
SELECT
p.product_name,
SUM(f.sales_amount) AS sales_amount
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY sales_amount DESC
LIMIT 5;

-- Which 5 categories generate the highest revenue with rank?
SELECT
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS category_rank,
p.category,
SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
LIMIT 5;

-- What are the 5 worst performing products in terms of sales?
SELECT
p.product_name,
SUM(f.sales_amount) AS sales_amount
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY sales_amount ASC
LIMIT 5;

-- Rank which are the 5 worst performing sub categories with respect to revenue generated?
SELECT
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) ASC) AS subcategory_rank,
p.subcategory,
SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
ON f.product_key = p.product_key
GROUP BY p.subcategory
LIMIT 5;

-- Find the top 10 customers who have generated the highest revenue
SELECT
	c.first_name,
	c.last_name,
	f.customer_key,
	SUM(sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
ON f.customer_key = c.customer_key
GROUP BY first_name, last_name, customer_key
ORDER BY total_revenue DESC
LIMIT 10;

-- 3 customers with the fewest orders places
SELECT
	f.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT f.order_number) AS total_orders
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
ON f.customer_key = c.customer_key
GROUP BY first_name, last_name, customer_key
ORDER BY total_orders
LIMIT 3;
